import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NodesProvider } from "@/context/nodesProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NodesProvider>
        <body className={inter.className}>{children}</body>
      </NodesProvider>
    </html>
  );
}
